import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

const JOB_TYPE_LABELS: Record<string, string> = {
  full_time: '正社員（常勤）',
  part_time: 'パート（非常勤）',
  spot: 'スポット',
};

const FEE_DESCRIPTIONS: Record<string, string> = {
  full_time: '年収の30%',
  part_time: '月給の100%',
  spot: '日給の10%',
};

export async function POST(request: Request) {
  try {
    const {
      placementId,
      invoiceNumber,
      facilityName,
      workerName,
      jobType,
      agreedSalary,
      feeRate,
      feeAmount,
      placementDate,
    } = await request.json();

    const doc = new jsPDF();
    const brandColor: [number, number, number] = [0, 196, 204]; // #00c4cc

    // --- Header ---
    doc.setFontSize(20);
    doc.setTextColor(...brandColor);
    doc.text('INVOICE', 20, 25);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Roots Recruitment', 20, 32);

    // --- Invoice meta ---
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(`Invoice No: ${invoiceNumber || placementId?.slice(0, 8) || 'N/A'}`, 140, 20);
    doc.text(`Date: ${new Date().toLocaleDateString('ja-JP')}`, 140, 26);
    doc.text(`Placement Date: ${placementDate || 'N/A'}`, 140, 32);

    // --- Divider ---
    doc.setDrawColor(...brandColor);
    doc.setLineWidth(0.5);
    doc.line(20, 38, 190, 38);

    // --- Bill To ---
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text('Bill To:', 20, 48);
    doc.setFontSize(10);
    doc.text(facilityName || 'N/A', 20, 55);

    // --- Worker info ---
    doc.setFontSize(11);
    doc.text('Worker:', 120, 48);
    doc.setFontSize(10);
    doc.text(workerName || 'N/A', 120, 55);

    // --- Fee breakdown table header ---
    const tableTop = 70;
    doc.setFillColor(245, 245, 245);
    doc.rect(20, tableTop, 170, 10, 'F');
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text('Description', 25, tableTop + 7);
    doc.text('Type', 90, tableTop + 7);
    doc.text('Rate', 125, tableTop + 7);
    doc.text('Amount', 160, tableTop + 7);

    // --- Fee row ---
    const rowY = tableTop + 18;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text('Recruitment Fee', 25, rowY);
    doc.text(JOB_TYPE_LABELS[jobType] || jobType || 'N/A', 90, rowY);
    doc.text(FEE_DESCRIPTIONS[jobType] || `${((feeRate || 0) * 100).toFixed(0)}%`, 125, rowY);
    doc.text(`${(feeAmount || 0).toLocaleString()} JPY`, 155, rowY);

    // --- Salary reference ---
    const salaryY = rowY + 10;
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Agreed Salary: ${(agreedSalary || 0).toLocaleString()} JPY`, 25, salaryY);

    // --- Total ---
    doc.setDrawColor(200, 200, 200);
    doc.line(20, salaryY + 8, 190, salaryY + 8);
    doc.setFontSize(14);
    doc.setTextColor(...brandColor);
    doc.text('Total:', 120, salaryY + 20);
    doc.setTextColor(0, 0, 0);
    doc.text(`${(feeAmount || 0).toLocaleString()} JPY`, 155, salaryY + 20);

    // --- Footer ---
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('* This invoice was automatically generated by Roots Recruitment.', 20, 270);
    doc.text('* Payment is due within 30 days of the invoice date.', 20, 276);

    // Return PDF as blob
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="invoice_${placementId?.slice(0, 8) || 'unknown'}.pdf"`,
      },
    });
  } catch (error) {
    console.error('create-invoice-pdf error:', error);
    return NextResponse.json(
      { error: '請求書PDF生成に失敗しました' },
      { status: 500 }
    );
  }
}
